#!/bin/bash
# foxglove - Launch Foxglove Bridge
set -euo pipefail

: "${RADAR_WS:=/workspace}"

set +u
source ~/env_setup.bash
set -u

ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765
