Camera:
  - camera_instrinsic:    
      camera_focal_length: 0.0015
      camera_focal_length_x: 0.000
      camera_focal_length_y: 0.000  
      camera_center_x: 0.000
      camera_center_y: 0.000
  # camera_extrinsic relative to the world coordinate system
  - camera_extrinsic:
      camera_rotation: [0.000, 0.000, 0.000]
      camera_translation: [0.000, 0.000, 0.000]

Lidar:
  # lidar_extrinsic relative to the world coordinate system
  - lidar_extrinsic:
      lidar_rotation: [0.000, 0.000, 0.000]
      lidar_translation: [0.000, 0.000, 0.000]
Camera_Lidar:
  # camera_lidar_extrinsic the camera coordinate system relative to the lidar coordinate system
  - camera_lidar_extrinsic:
      camera_lidar_rotation: [0.000, 0.000, 0.000]
      camera_lidar_translation: [0.000, 0.000, 0.000]
Model:
    model_name: "RMUC-2026-National"
    model_path: "/workspace/model/RMUC2026.fbx"
    model_type: "fbx"
